apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-simple
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb-simple
data:
  mongod.conf: |
    # Simple MongoDB configuration for Kubernetes
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    
    net:
      port: 27017
      bindIpAll: true
    
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    
    security:
      authorization: disabled
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-simple
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb-simple
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
        runAsNonRoot: true
      containers:
      - name: mongodb
        image: percona/percona-server-mongodb:8.0-community-k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONGODB_DATA_DIR
          value: /data/db
        - name: MONGODB_LOG_DIR
          value: /var/log/mongodb
        - name: MONGODB_CONFIG_DIR
          value: /etc/mongodb
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-logs
          mountPath: /var/log/mongodb
        - name: mongodb-config
          mountPath: /etc/mongodb/mongod.conf.template
          subPath: mongod.conf
          readOnly: true
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - liveness
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - readiness
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - /healthcheck.sh
            - startup
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 30
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 0
          capabilities:
            drop:
            - ALL
      volumes:
      - name: mongodb-data
        emptyDir: {}
      - name: mongodb-logs
        emptyDir: {}
      - name: mongodb-config
        configMap:
          name: mongodb-config
          defaultMode: 0644
      terminationGracePeriodSeconds: 30
      restartPolicy: Always